create database student;
use student;

CREATE TABLE CUSTOMERS
(Customer_no  INT(4),
LastName VARCHAR(10),
FirstName VARCHAR(10),
Address VARCHAR(20),
City VARCHAR(12),
State VARCHAR(2),
Zip VARCHAR(5),
Referred INT(4),
Region CHAR(2));


INSERT INTO CUSTOMERS
VALUES (1001, 'MORALES', 'BONITA', 'P.O. BOX 651', 'EASTPOINT', 'FL', '32328', NULL, 'SE');
INSERT INTO CUSTOMERS
VALUES (1002, 'THOMPSON', 'RYAN', 'P.O. BOX 9835', 'SANTA MONICA', 'CA', '90404', NULL, 'W');
INSERT INTO CUSTOMERS 
VALUES (1003, 'SMITH', 'LEILA', 'P.O. BOX 66', 'TALLAHASSEE', 'FL', '32306', NULL, 'SE'); 
INSERT INTO CUSTOMERS 
VALUES (1004, 'PIERSON', 'THOMAS', '69821 SOUTH AVENUE', 'BOISE', 'ID', '83707', NULL, 'NW'); 
INSERT INTO CUSTOMERS 
VALUES (1005, 'GIRARD', 'CINDY', 'P.O. BOX 851', 'SEATTLE', 'WA', '98115', NULL, 'NW'); 
INSERT INTO CUSTOMERS 
VALUES (1006, 'CRUZ', 'MESHIA', '82 DIRT ROAD', 'ALBANY', 'NY', '12211', NULL, 'NE'); 
INSERT INTO CUSTOMERS 
VALUES (1007, 'GIANA', 'TAMMY', '9153 MAIN STREET', 'AUSTIN', 'TX', '78710', 1003, 'SW'); 
INSERT INTO CUSTOMERS 
VALUES (1008, 'JONES', 'KENNETH', 'P.O. BOX 137', 'CHEYENNE', 'WY', '82003', NULL, 'N'); 
INSERT INTO CUSTOMERS 
VALUES (1009, 'PEREZ', 'JORGE', 'P.O. BOX 8564', 'BURBANK', 'CA', '91510', 1003, 'W'); 
INSERT INTO CUSTOMERS 
VALUES (1010, 'LUCAS', 'JAKE', '114 EAST SAVANNAH', 'ATLANTA', 'GA', '30314', NULL, 'SE'); 
INSERT INTO CUSTOMERS 
VALUES (1011, 'MCGOVERN', 'REESE', 'P.O. BOX 18', 'CHICAGO', 'IL', '60606', NULL, 'N');  
INSERT INTO CUSTOMERS 
VALUES (1012, 'MCKENZIE', 'WILLIAM', 'P.O. BOX 971', 'BOSTON', 'MA', '02110', NULL, 'NE'); 
INSERT INTO CUSTOMERS 
VALUES (1013, 'NGUYEN', 'NICHOLAS', '357 WHITE EAGLE AVE.', 'CLERMONT', 'FL', '34711', 1006, 'SE'); 
INSERT INTO CUSTOMERS 
VALUES (1014, 'LEE', 'JASMINE', 'P.O. BOX 2947', 'CODY', 'WY', '82414', NULL, 'N'); 
INSERT INTO CUSTOMERS 
VALUES (1015, 'SCHELL', 'STEVE', 'P.O. BOX 677', 'MIAMI', 'FL', '33111', NULL, 'SE'); 
INSERT INTO CUSTOMERS 
VALUES (1016, 'DAUM', 'MICHELL', '9851231 LONG ROAD', 'BURBANK', 'CA', '91508', 1010, 'W'); 
INSERT INTO CUSTOMERS 
VALUES (1017, 'NELSON', 'BECCA', 'P.O. BOX 563', 'KALMAZOO', 'MI', '49006', NULL, 'N'); 
INSERT INTO CUSTOMERS 
VALUES (1018, 'MONTIASA', 'GREG', '1008 GRAND AVENUE', 'MACON', 'GA', '31206', NULL, 'SE'); 
INSERT INTO CUSTOMERS 
VALUES (1019, 'SMITH', 'JENNIFER', 'P.O. BOX 1151', 'MORRISTOWN', 'NJ', '07962', 1003, 'NE'); 
INSERT INTO CUSTOMERS 
VALUES (1020, 'FALAH', 'KENNETH', 'P.O. BOX 335', 'TRENTON', 'NJ', '08607', NULL, 'NE'); 




CREATE TABLE PUBLISHER 
(PubID INT(2), 
Name VARCHAR(23), 
Contact VARCHAR(15), 
Phone VARCHAR(12)) engine=innodb;

 
INSERT INTO PUBLISHER 
VALUES(1,'PRINTING IS US','TOMMIE SEYMOUR','000-714-8321'); 
INSERT INTO PUBLISHER 
VALUES(2,'PUBLISH OUR WAY','JANE TOMLIN','010-410-0010'); 
INSERT INTO PUBLISHER 
VALUES(3,'AMERICAN PUBLISHING','DAVID DAVIDSON','800-555-1211'); 
INSERT INTO PUBLISHER 
VALUES(4,'READING MATERIALS INC.','RENEE SMITH','800-555-9743'); 
INSERT INTO PUBLISHER 
VALUES(5,'REED-N-RITE','SEBASTIAN JONES','800-555-8284'); 
 

CREATE TABLE AUTHOR 
(AuthorID VARCHAR(4), 
Lname VARCHAR(10), 
Fname VARCHAR(10)) engine=myisam; 
 
INSERT INTO AUTHOR 
VALUES ('S100','SMITH', 'SAM'); 
INSERT INTO AUTHOR 
VALUES ('J100','JONES','JANICE'); 
INSERT INTO AUTHOR 
VALUES ('A100','AUSTIN','JAMES'); 
INSERT INTO AUTHOR 
VALUES ('M100','MARTINEZ','SHEILA'); 
INSERT INTO AUTHOR 
VALUES ('K100','KZOCHSKY','TAMARA'); 
INSERT INTO AUTHOR 
VALUES ('P100','PORTER','LISA'); 
INSERT INTO AUTHOR 
VALUES ('A105','ADAMS','JUAN'); 
INSERT INTO AUTHOR 
VALUES ('B100','BAKER','JACK');  
INSERT INTO AUTHOR 
VALUES ('P105','PETERSON','TINA'); 
INSERT INTO AUTHOR 
VALUES ('W100','WHITE','WILLIAM'); 
INSERT INTO AUTHOR 
VALUES ('W105','WHITE','LISA'); 
INSERT INTO AUTHOR 
VALUES ('R100','ROBINSON','ROBERT'); 
INSERT INTO AUTHOR 
VALUES ('F100','FIELDS','OSCAR'); 
INSERT INTO AUTHOR 
VALUES ('W110','WILKINSON','ANTHONY');  